[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
creature = "5fbkSTigPB76nwTW2Pea4D8oKG5Y3LhjaNWMLCGqoyjL"
battle = "8cfzkYSLCAmFzYNVszjQS7gg4vt4aX1QHvo6FnBHsTXD"
token = "PuvPe2KwWqMz5Z5cBfqiaE5a8uPtmVNKbKJhgkNwXMq"
marketplace = "BCfwGoEyzqkpDcSoXVVRgeHDf59fZZfcS4uc8X948PxF"

[programs.devnet]
creature = "5fbkSTigPB76nwTW2Pea4D8oKG5Y3LhjaNWMLCGqoyjL"
battle = "8cfzkYSLCAmFzYNVszjQS7gg4vt4aX1QHvo6FnBHsTXD"
token = "PuvPe2KwWqMz5Z5cBfqiaE5a8uPtmVNKbKJhgkNwXMq"
marketplace = "BCfwGoEyzqkpDcSoXVVRgeHDf59fZZfcS4uc8X948PxF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
